wordpress_1  | writing new private key to 'server.key'
wordpress_1  | -----
srcs_db_1 exited with code 0
Exception in thread Thread-4:
Traceback (most recent call last):
  File site-packages/docker/api/client.py, line 261, in _raise_for_status
  File site-packages/requests/models.py, line 940, in raise_for_status
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: http+docker://localhost/v1.22/containers/e72a40076160c20cfffc1eeb237edbcc9184880bc81a88fc71f9345e87c9d533/attach?logs=0&stdout=1&stderr=1&stream=1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File threading.py, line 916, in _bootstrap_inner
  File threading.py, line 864, in run
  File compose/cli/log_printer.py, line 233, in watch_events
  File compose/container.py, line 215, in attach_log_stream
  File compose/container.py, line 307, in attach
  File site-packages/docker/utils/decorators.py, line 19, in wrapped
  File site-packages/docker/api/container.py, line 61, in attach
  File site-packages/docker/api/client.py, line 400, in _read_from_socket
  File site-packages/docker/api/client.py, line 311, in _get_raw_response_socket
  File site-packages/docker/api/client.py, line 263, in _raise_for_status
  File site-packages/docker/errors.py, line 31, in create_api_error_from_http_exception
docker.errors.APIError: 409 Client Error: Conflict (bcontainer e72a40076160c20cfffc1eeb237edbcc9184880bc81a88fc71f9345e87c9d533 is restarting, wait until the container is running)

srcs_nginx_1 exited with code 137
